export const colors = {
  background: '#E0F2FE',
  cardBackground: '#FFFFFF',
  primary: '#4facfe',
  secondary: '#E0F2FE',
  accent: '#4facfe',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  success: '#00f2fe',
  warning: '#F5A623',
  error: '#D9534F',
  gradientStart: '#E0F2FE',
  gradientEnd: '#FDF2F8',
  shadowColor: '#4facfe',
  inputBackground: '#F0F7FF',
  borderColor: '#D6E8F7',
};
